version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
        default: "15.10.0"
    docker:
      - image: cimg/node:<< parameters.node-version >>
    parallelism: 4
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npm run test-ci
    
  trigger-project-b-pipeline:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: Ping another pipeline
          command: |
            CREATED_PIPELINE=$(curl --request POST \
              --url https://circleci.com/api/v2/project/circleci/GdhqZrYuhbfi1kTzJr2WBQ/EdH2esqWx17NJH3oDzPoK9/pipeline \
              --header "Circle-Token: $CIRCLECI_API_KEY" \
              --header "content-type: application/json" \
              --data '{"branch":"main","parameters":{"triggering-pipeline-id":"<< pipeline.id >>"}}' \
            | jq -r '.id'
            )

            echo "my created pipeline"
            echo $CREATED_PIPELINE

            mkdir ~/workspace
            echo $CREATED_PIPELINE > pipeline.txt
      - persist_to_workspace:
          root: .
          paths: 
            - pipeline.txt  

  node-test-and-deploy:
    jobs:
      - build-and-test
      - trigger-project-b-pipeline:
          context: 
            - circleci-api
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - wait-for-triggered-pipeline:
          type: approval
          requires: 
            - trigger-project-b-pipeline
